[advisories]
version = 2
db-urls = ["https://github.com/rustsec/advisory-db"]

unmaintained = "all"
unsound = "all"
yanked = "warn"
ignore = [
    #"RUSTSEC-0000-0000",
]

[licenses]
version = 2
# List of explictly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
]

# Lint level for licenses considered copyleft
confidence-threshold = 0.925

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"

[sources]
unknown-registry = "warn"
unknown-git = "warn"

allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
