name: "ci-msrv"
on:
  pull_request:
  push:
    branches:
      - master
      - main
      - staging # for Bors
      - trying # for Bors
  schedule:
    - cron: '00 05 * * *'
jobs:
  msrv:
    name: msrv
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        build: [ lib, macro ]
        include:
          - build: lib
            path: "."

          - build: macro
            path: "yare-macro"
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: install_rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: install_cargo_msrv
        run: cargo install cargo-msrv --no-default-features
      - name: version_of_cargo_msrv
        run: cargo msrv --version
      - name: run_cargo_msrv
        run: cargo msrv --path ${{ matrix.path }} --ignore-lockfile --output-format json verify  -- cargo test